# Generated by Django 2.0.6 on 2021-08-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
